lib/fog/core/attributes.rb
spec/fog_attribute_spec.rb

fix #requires_one

---

lib/fog/core/collection.rb
lib/fog/core/model.rb
lib/fog/core/ssh.rb
lib/fog/formatador.rb
spec/formatador_spec.rb

Prefix `Formatador.new` call  with scope resolution op so we don't call `Fog::Formatador.new`

Use Fog::Formatador

---

lib/fog/baremetal.rb
lib/fog/core.rb

Adding OpenStack Ironic service for managing baremetals.

Add OpenStack Ironic service

---

lib/fog/core/collection.rb

true && super  =>  super

---

lib/fog/core/connection.rb
spec/connection_spec.rb

In relation to: https://github.com/fog/fog/issues/3433#issuecomment-73893922

Allow apps to pass along own user agent

---

README.md

Fix link of README.md

---

lib/fog/core.rb

Using relative paths

---

lib/fog/compute.rb

This adds version selection for the digital ocean api v2

Adding support to DigitalOcean v2

---

spec/core/model_spec.rb

Add more testing for #149 and fixup

Add more testing for #149 and fixup

---

lib/fog/compute.rb

API v1 is at eol.More information here
https://developers.digitalocean.com/documentation/v1/ 
closes fog/fog#3782

Make digitalocean v2 api default

---

lib/fog/compute.rb

I have added cloudatcost to fog.
https://github.com/fog/fog/pull/3811

Added cloudatcost to fog core

---

fog-core.gemspec

than older versions that require it. Fixes #206 for the time being.
/cc @BanzaiMan @geemus

fixes #206 stop gap. better 2.4 above not working

---

lib/fog/core/cache.rb

A small followup for caching. Other than this #204 seems to be smooth for various different resources. 
/cc @icco @plribeiro3000

use homedirectory, not actual ~ as for cache sandbox.

---

lib/fog/core/errors.rb
lib/fog/test_helpers/mock_helper.rb

We update provider dependencies to enable [kubevirt](http://www.kubevirt.io/) provider.

Introduce kubevirt provider

---

changelog.md

When viewing the file in IDE, formatting not important but on www,
where markdown is rendered to HTML, formatting really helps
[ci skip]

Docs: Format lists in changelog.md

---

changelog.md

- Distinguish which changes are breaking
- Explain what "Fix association reload" means

Docs: Update changelog re: 2.0.0

---

lib/fog/core/attributes.rb

closes #236 
cc/ @gildub @geemus

Deprecate Attributes not defined by DSL

---

changelog.md

https://github.com/fog/fog-core/blob/v2.1.2/changelog.md
https://github.com/sue445/fog-core/blob/ba73cbb13118bd43fa96b0377ad10bff04b439de/changelog.md

Apply list format to changelog

---

.rubocop_todo.yml
lib/fog/compute/models/server.rb
lib/fog/core/cache.rb
lib/fog/core/uuid.rb

Another small portion of changes + rubocop (double negation).

Remove ruby 1x

---

Rakefile
fog-core.gemspec
spec/spec_helper.rb

Ping @tokengeek  and @geemus 
This fixes #290 
I think this should be everything.

Remove remaining coveralls bits from code
