lib/fog/core/service.rb
On ruby 2.2 the changed line can emit a warning along the lines of
> Comparable#== will no more rescue exceptions of #<=> in the next release.
One case where this happens is when value is an instance of Time. I don't this this change affects the case we're trying to capture (at least not the one mentioned in the specs) but it avoids the warning.
=> value is an arbitrary object and may not implement #== with string arg

lib/fog/core/attributes/time.rb, spec/fog_attribute_spec.rb
Some libraries (like Rails) will monkey patch String to add the
`to_time` method.  That means this method will function differently
depending on who monkey patched String first.  For example, [Rails changed it's default on `to_time`](https://github.com/rails/rails/commit/b79adc4323ff289aed3f5787fdfbb9542aa4f89f) to parse with regard to local time rather than UTC, which means that if you use fog with Rails, the dates returned will differ depending on which version of Rails you use.
If the object is a String, lets parse it so that the function has a
consistent return value for a given input.
=> only check for `to_time` as a last resort.

lib/fog/formatador.rb, spec/formatador_spec.rb
This is work to fix #138 
We check if the object passed to `Fog::Formatador` is `Enumerable` rather than checking for `map`
The class method is now used for all `Fog::Model#inspect` calls (whilst it used to just be used for collections).
This fixes fog/fog-brightbox#17
=> [GH #138] Fix Formatador for objects defining `map`

lib/fog/core/wait_for.rb, spec/wait_for_spec.rb
Currently, if the final iteration in wait_for happens after timeout is exceeded and the yield returns true, an exception is still raised despite the successful block execution.  The included spec test fails with the existing code and passes with the new code, so it is a regression test, I guess.
=> Don't raise an exception if the final yield returns true

lib/fog/core/model.rb
I've been working on speeding up our test suite over in `fog-google` using VCR, and it would be extremely helpful if I could globally override the default interval for `wait_for`.  In this case, it's also a case of a [magic number](http://en.wikipedia.org/wiki/Magic_number_%28programming%29#Unnamed_numerical_constants), which, as far as I can tell, should be gotten rid of.
This is also more consistent with the definition of `Fog.wait_for` [here](https://github.com/fog/fog-core/blob/master/lib/fog/core/wait_for.rb).
=> use Fog.interval instead of constant in Model.wait_for

lib/fog/core/model.rb, spec/core/model_spec.rb
Closes #148
N.B. This implementation means that the following will happen:
```
> a = Fog::Model.new
> b = Fog::Model.new
> a == b
=> true
> a.save
> b.save
> a == b
=> false
```
It wasn't clear to me if two unsaved models should be equal or not, so I made a judgement call.  I'm definitely open to ideas.
=> Add Fog::Model equality based on identity

lib/fog/storage.rb
Mail 2.6.1+ has a columnar store that only loads the data that is needed for a drastically reduced memory footprint. cc/ @jeremyevans @halostatue
=> Decrease Fog Memory footprint

lib/fog/account.rb, lib/fog/baremetal.rb, lib/fog/billing.rb, lib/fog/cdn.rb, lib/fog/image.rb, lib/fog/metering.rb, lib/fog/monitoring.rb, lib/fog/network.rb, lib/fog/orchestration.rb, lib/fog/support.rb, lib/fog/volume.rb, lib/fog/vpn.rb
I was trying to use Fog::Account on fog-softlayer and I was always getting this message error:
``` softlayer has no account service (ArgumentError) ```
So, when I take a look at this service, I've seen that it always returning this message if provider was different from :stormondemand.
Then, I fixed it!
=> Fix account service to recognize all providers

lib/fog/account.rb, lib/fog/baremetal.rb, lib/fog/billing.rb, lib/fog/cdn.rb, lib/fog/compute.rb, lib/fog/core.rb, lib/fog/core/services_mixin.rb, lib/fog/dns.rb, lib/fog/identity.rb, lib/fog/image.rb, lib/fog/metering.rb, lib/fog/monitoring.rb, lib/fog/network.rb, lib/fog/orchestration.rb, lib/fog/storage.rb, lib/fog/support.rb, lib/fog/volume.rb, lib/fog/vpn.rb
Only rescue errors related to loading and finding components
Allow connection errors to bubble up to the caller.  Previous changes were rescuing connection errors and re-raising them as ArgumentErrors leading people to believe that "openstack has no network service" for example. However, this was not the case, openstack does have a network service registered in fog, the proper library was loaded, but there was an issue connecting to the server.
See changes in: https://github.com/fog/fog-core/commit/36e2824c8467402697edc188cc8779ced659e31c
=> Refactor services and fix errors

lib/fog/core/attributes.rb
It's nice to have name of the identity attribute exposed as
public. So it can be used e.g. for selecting uniq elements
of the Fog::Collection
=> Expose the name of the identity attribute

fog-core.gemspec
Looking at the dep graph, it's fog-core's dependency net-ssh, which just updated a couple of hours ago:
https://rubygems.org/gems/net-ssh/
3.0.1 - September 25, 2015 (177 KB)
This breaks gem deps on Ruby <2.0
=> Locking the net-ssh for Ruby <2.0

fog-core.gemspec, lib/fog/compute/models/server.rb, lib/fog/core/scp.rb, lib/fog/core/ssh.rb
first stab at making 1.9 still a thing. Might even remove the ruby require to allow this to more easily go onto 1.x series (and then get back onto the 2.x train).
=> loosen requirements around net-ssh/net-scp and ruby version

lib/fog/core/mock.rb
If the service classes haven't been loaded yet, they cannot have been used in any mocked tests, so there's nothing to be gained by loading them to clear out state. Eager-loading isn't just an efficiency issue -- eagerly loading classes may unnecessarily conflict with the rest of the dependency graph and can cause contrived breakages if a service doesn't run particularly well on a given platform.
=> Don't eagerload auto-loaded service classes in Fog::Mock.reset.

lib/fog/compute.rb
Remove hp from the list since their service has shutdown and fog/fog no longer has it.
Refer fog/fog#3854
=> Remove hp from the providers list

lib/fog/storage.rb
Re-raise LoadError when unable to require `mime/types` rather than exiting - the latter causes any application *using* fog to exit, which is a really crappy thing to run in to on accident for a web app
=> Re-raise LoadError rather than exiting

lib/fog/core/services_mixin.rb
Use `Notfound` error instead of `ArgumentError` when the service was not found,
It could be very nice and more comprehensive.
Project like MIQ try to catch NotFound for not found service in provider catalog
https://github.com/Ladas/manageiq/blob/c836fdf2567122193ec54d237bc07df814abe407/gems/pending/openstack/openstack_handle/handle.rb#L75
=> change service not found error type to Fog::Errors::Notfound

lib/fog/storage.rb, spec/storage_spec.rb
I hit this issue in tests using fog-aws mock services.
=> fix string freeze issue for ruby 2.3

lib/fog/storage.rb
A recent change (c2e720e) allowed you to pass frozen strings as the body to a new file without raising a `RuntimeError` when fog tried to call `force_encoding` on it. This is fantastic, and I can't wait for the next release so we can take advantage of it.
One thing I thought might be worth discussing is that `dup`ing every time could have a performance impact, so we could just do it when the string is frozen, and otherwise keep the original behaviour.
Does this sound sensible?
I've not written a test for this because there's already one to test the correct behaviour when we pass a frozen string. If you think there's something more we could cover with a test let me know.
=> Only dup strings that are frozen

lib/fog/core/services_mixin.rb
- Disabled inherit option on `const_get` in `service_provider_constant` so it doesn't search the ancestors and `Object`.
This should fix https://github.com/fog/fog-google/issues/123
/CC  @geemus @tokengeek @plribeiro3000 PTAL, since I'm less familiar with `fog-core` code.
=> Fixing namespace constant detection

.travis.yml, Gemfile18, lib/fog/core/services_mixin.rb
Second method argument not available in ruby < 1.9
```
tests/models/cdn/distribution_tests.rb
Fog::CDN[:aws] | distribution (aws, cdn)
wrong number of arguments (2 for 1) (ArgumentError)
/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/fog-core-1.41.0/lib/fog/core/services_mixin.rb:34:in `const_get'
/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/fog-core-1.41.0/lib/fog/core/services_mixin.rb:34:in `service_provider_constant'
/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/fog-core-1.41.0/lib/fog/core/services_mixin.rb:15:in `new'
/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/fog-core-1.41.0/lib/fog/core/services_mixin.rb:4:in `[]'
./tests/models/cdn/distribution_tests.rb:3
```
https://travis-ci.org/fog/fog-aws/jobs/141660726
=> fix #const_get lookup arguments

lib/fog/compute.rb, lib/fog/core/version.rb
@geemus I have removed version2 of digitalocean to clean up the fog-digitalocean gem. https://github.com/fog/fog-digitalocean/pull/9 has the changes for in the fog-digitalocean gem
=> Remove digitalocean version 2 and bump version

lib/fog/compute.rb
Add DigitalOcean provider, but remove the trailing '_v2' from require.
It is no longer there in the fog-digitalocean provider gem.
=> Add DigitalOcean provider back

Gemfile, fog-core.gemspec, lib/fog/core/cache.rb, lib/fog/core/collection.rb, lib/fog/core/model.rb, spec/core/cache_spec.rb, spec/service_spec.rb
Hey @geemus regarding the caching issue @ https://github.com/fog/fog-aws/issues/354#issuecomment-286789702
To take care of before merging:
Works with a test CLI application using this fork. You can see usage in the test file, the gist is:
- Expiring cache:
```
[1] pry> Fog::Cache.expire_cache!(Fog::Compute::AWS::Server, compute)
=> ["/tmp/Fog_Compute_AWS_Real/us-east-1/Fog_Compute_AWS_Server"]
```
- Raises on empty cache:
```
[2] pry> ss = Fog::Cache.load(Fog::Compute::AWS::Server, compute)
Fog::Cache::CacheNotFound: Fog::Cache::CacheNotFound
from /Users/shai/r/fog-core/lib/fog/core/cache.rb:15:in `load'
```
- Dumping an instance:
```
[1] pry> s = c.servers.sample; s.id
=> "i-0569a70ae6f47d229"
[2] pry> s.cache.dump
=> 2371
```
- On disk:
```
shai@adsk-lappy ~   % tree …
```
=> Add file yml caching to models

Gemfile, lib/fog/core/cache.rb, spec/core/cache_spec.rb
Not important to merge/release at this point, as there might be some more iterations to go through. But logging this here so I don't forget.
There might be some more fixes of these sorts of things over time as usage increases.
=> Cache fixes

fog-core.gemspec, lib/fog/compute/models/server.rb, spec/compute/models/server_spec.rb, spec/core/cache_spec.rb, spec/fog_attribute_spec.rb
See issue fog/fog-aws#372
For AWS Spot Request, instances never complete the `#setup` process eventually timing out through the `#wait_for` block because the default 8s is apparently not long enough to get the ssh connection. Through testing 11s seemed to work, but this is likely highly variable for regions, instance types, images, and providers.
This change implements a 1.5 increase in timeout each time `#sshable?` is called, capped at 60s. If a successful connection is made, then the timeout is reset to the initial value.
I tried to keep this as simple as possible. This solves the problem for AWS Spot Requets and does not adversely affect regular AWS instances. I have not tested this with other providers, but a quick check it didn't seem like this would be a problem.
The only concern I …
=> Add exponential increase on timeout in #sshable? for services that do not respond in 8s

.travis.yml, Gemfile.1.8.7, Gemfile.1.9.3, README.md, fog-core.gemspec, lib/fog/core/services_mixin.rb, lib/fog/test_helpers/collection_helper.rb, spec/storage_spec.rb
According to README, fog-core does not support Ruby 1.9. Users
requiring it should use the fog gem.
=> Drop Ruby<2 support

lib/fog/core/scp.rb, lib/fog/core/ssh.rb
In response to https://github.com/net-ssh/net-ssh/commit/c3fbcdc882f6763fa718f6adbd9d1d60eaf04b62
=> Updating net-ssh parameter names

fog-core.gemspec, lib/fog/storage.rb
This adds mime-types as runtime dependency into gemspec, which is required in https://github.com/fog/fog-core/blob/master/lib/fog/storage.rb
It wasn't added before because of fog's support of Ruby 1.9.3. 
Support for Ruby 1.9.3 was removed from fog in https://github.com/fog/fog/pull/3974
=> Add missing runtime dependency declaration to gemspec

lib/fog/test_helpers/mock_helper.rb
```
/lib/fog/test_helpers/mock_helper.rb:69: warning: key :libvirt_uri is duplicated and overwritten on line 91
```
=> Fix warning: key :libvirt_uri is duplicated

lib/fog/core/model.rb
There is no guarantee that `collection.get` will return an object and the `nil` case should be handled appropriately.
=> fix nil fetch on object reload

CONTRIBUTING.md, lib/fog/core/ssh.rb
This is an actual refactoring, meaning that it should change nothing :grin:
it's just extracting some private methods to make the constructor
easier to read.
=> Extract private methods from Fog::SSH::Real constructor

lib/fog/core/provider.rb, lib/fog/core/services_mixin.rb, spec/compute_spec.rb, spec/identity_spec.rb, spec/storage_spec.rb
All classes defined from within a Gem should be inside its own namespace
to avoid conflicts with other gems
cc/ @geemus @icco @Temikus @lanej @fog/core 
This will be the first PR of many to
* Achieve minimum consistency across all providers
* Implement some best practices
* Improve loading of the libraries by using bundle instead of manually requiring it
=> Force Gem Best Practice

lib/fog/core/connection.rb
Setting `@path_prefix` within a condition meant it was not initialized
to `nil` in cases when it was not passed in. This triggered warnings
when Ruby was showing them and the variable was used.
`Hash#delete` already returns `nil` when the key is missing so that can
be used to initialize it correctly.
=> Fix `@path_prefix` not initialized warning

lib/fog/core/ssh.rb
```
Traceback (most recent call last):
6: from check_dqa_vm.rb:81:in `<main>'
5: from /usr/local/bundle/gems/fog-core-2.1.1/lib/fog/compute/models/server.rb:88:in `ssh'
4: from /usr/local/bundle/gems/fog-core-2.1.1/lib/fog/core/ssh.rb:9:in `new'
3: from /usr/local/bundle/gems/fog-core-2.1.1/lib/fog/core/ssh.rb:9:in `new'
2: from /usr/local/bundle/gems/fog-core-2.1.1/lib/fog/core/ssh.rb:40:in `initialize'
1: from /usr/local/bundle/gems/fog-core-2.1.1/lib/fog/core/ssh.rb:104:in `build_options'
/usr/local/bundle/gems/fog-core-2.1.1/lib/fog/core/ssh.rb:121:in `merge_default_options_into': undefined local variable or method `otps' for #<Fog::SSH::Real:0x000055da87f1eb60> (NameError)
Did you mean?  opts
```
=> Fixup typo otps -> opts (2.1.1 error)

lib/fog/core/provider.rb, lib/fog/core/services_mixin.rb
This deprecation message will be shown to normal people who
know nothing about this issue, so it's important that we give
them enough information.
=> Explain deprecation of service/provider format

lib/fog/core/services_mixin.rb
I was hitting issue Fog::Service::NotFound: ovirt has no compute service
when trying to use fog-ovirt and there was no indication of what could be
wrong. Eventually, I've figured out, that there was issue with
dependencies inside fog-ovirt, that we were suppressing.
This patch adds logging around the requiring the provider so that this
issues are easier to debug later.
There are several issues in the past around the 'no compute service' that would benefit from more logging,
such as:
- https://github.com/fog/fog-xenserver/issues/60
- https://github.com/fog/fog-google/issues/170
- https://github.com/fog/fog-openstack/issues/181
- https://github.com/mitchellh/vagrant-aws/issues/505
=> Log issues when loading providers

lib/fog/core/scp.rb, lib/fog/core/ssh.rb
=> Use :never in ssh/scp verify_host_key option

lib/fog/core/provider.rb
I'm not sure about having two keys for the same provider here so i'm open this to start a discussion about the actual problem.
It all started with fog/fog-internet-archive#2 where `shindot` could not load some files.
When we started extracting providers we gave them proper names like:
- `bare_metal_cloud` over `baremetalcloud`
- `go_grid` over `gogrid`
- `internet_archive` over `internetarchive`
- `storm_on_demand` over `stormondemand`
- `vcloud_director` over `vclouddirector`
The problem lies in [here](https://github.com/fog/fog-core/blob/567982afac90edfd880e5b38c584062302224dcc/lib/fog/core/provider.rb#L11-L14):
```ruby
def self.extended(base)
provider = base.to_s.split("::").last
Fog.providers[provider.downcase.to_sym] = provider
end
```
This code generates keys based on the class …
=> feat(Provider): Underscore name

lib/fog/core/provider.rb
This method was defined on the instance level, not the class level, so `Provider.extends` couldn't get to it. Broke our build when we attempted to update to v2.2.1.
=> Fix Call to `#underscore_name`

lib/fog/core/provider.rb, lib/fog/core/services_mixin.rb
@geemus Now that we got that release i was able to figure out what was wrong with the loading at fog/fog-internet-archive#2.
~~I will point that PR to this branch and see how it goes. Will check here later.~~
EDIT: 
It works now. we had two minor issues:
* The alias provider name was not a symbol
* The guard clause was not looking for the non aliased name
=> fix(Provider): lookup

lib/fog/core/logger.rb
We need to enable DEBUG logging for fog-azure-rm but we cannot necessarily set the DEBUG environment variable for fog-azure-rm because that would log the complete HTTP body because of https://github.com/fog/fog-azure-rm/blob/9da5cc04189cd1ec751c5bc1e2f5406ce6b179d0/lib/fog/azurerm/storage.rb#L96-L97.
Proposal is to instead offer another env variable 'FOG_DEBUG' to enable only logging on fog-azure-rm level.
Similar change was proposed here: https://github.com/fog/fog-azure-rm/pull/431
But there it is done for branch fog-arm-cf only...
=> add fog-specific debug var

changelog.md
Otherwise the markdown squashes all the items to same line
=> Fix formatting of v2.2.4 changelog items

lib/fog/core/provider.rb, spec/compute_spec.rb, spec/identity_spec.rb, spec/storage_spec.rb
This change avoids loading unnecessary service classes when the service is defined with `autoload`, such as fog-aws.
fog-aws  uses `autoload` to load each service to avoid loading unnecessary service. By the `autoload`s, the end-users can reduce startup time and memory usage.
But the `autoload`s don't work actually. fog-aws loads all services even if the user doesn't need all services.
Because fog-core evaluates all services' constants with `eval` method. The evaluation loads unnecessary code unexpectedly.
Use `const_efined?` instead of `eval`. `const_defined?` method checks constant existence without loading the code.
Note that I also reorder class definitions in the test. It reduces unexpected warnings, such as `Unable to load ...`. It doesn't the test result, so I'll revert the test …
=> Avoid loading unnecessary service via autoload

.github/workflows/ruby.yml
Hi, I notice that MRI Ruby head is failing here, but Truffleruby head passes
=> Add Truffleruby head to CI

lib/fog/core/cache.rb, spec/compute/models/server_spec.rb, spec/core/cache_spec.rb
Some collections also have attributes. It is better to cache collection's attributes too and properly restore model and collection.
For example, DNS `Zone` model has `Records` collection. This collection requires `zone_id` attribute to operate: get all records by `zone_id`, get record by `zone_id` and record `identity`, etc. When we load from cache a `Record` Fog creates collection for this model without any attributes.
Also when cache is not `valid_for_load?` let display which keys are missing.
=> Cache and restore collection attributes

lib/fog/core/model.rb, spec/core/model_spec.rb
Please, do not squash commits when (if) merging.
Add methods `#create`, `#update`, `#save`, `#destroy` explicitly.
Be more consistent with return values.
Add `filter_attributes` helper method.
Commit messages below:
---
Model methods like #save or #destroy are implicit: they only mentioned
in README but explicitly used by framework. Let define them also
explicitly so developer knows exactly what to implement.
This change is not breaking change, because either method is already
defined in child class or is not used at all.
Another goal is to make return values consistent.
---
It is just handy method to easily get a sub-set of attributes.
For example, my model has 10+ attributes, but when creating/updating
model I need only a few of them:
Code:
...
attribute :name
attribute :value
attribute …
=> Model methods

lib/fog/core/attributes.rb, lib/fog/core/attributes/default.rb, spec/fog_attribute_spec.rb
It is just handy method to easily get a sub-set of attributes. For example, my model has 10+ attributes, but when creating/updating model I need only a few of them:
Code:
...
attribute :name
attribute :value
attribute :comment
attribute :type
...
service.create_entity(filter_attributes(:name, :value, :type))
=> Add filter_attributes method

lib/fog/core/cache.rb, spec/core/cache_spec.rb, spec/spec_helper.rb
Two commits, no need to squash.
Fixes cache load with aliases/anchors.
Uses temporary directory for cache tests.
=> Cache load

lib/fog/core/cache.rb
SANDBOX and namespace_prefix can have their own register. We shouldn't downcase whole path.
Without this patch
Case 1: $HOME == '/home/Domain_User' - will fail (mkdir - permission denied /home/domain_user)
Case 2: namespace_prefix == 'MyService' - will create ~/.fog-cache/myservice
=> Fix wrong Cache#namespace path

lib/fog/test_helpers/minitest/assertions.rb, lib/fog/test_helpers/minitest/expectations.rb, spec/service_spec.rb
The `MiniTest` was renamed to `Minitest`:
https://github.com/minitest/minitest/commit/9a57c520ceac76abfe6105866f8548a94eb357b6
And the `MiniTest` constant is now loaded just when `MT_COMPAT` environment variable is set:
https://github.com/minitest/minitest/commit/a2c6c18570f6f0a1bf6af70fe3b6d9599a13fdd6
=> Fix compatibility with Minitest 5.19+

.github/workflows/ci.yml, lib/fog/compute.rb, lib/fog/core.rb, lib/fog/core/mock.rb, lib/fog/core/provider.rb, lib/fog/core/service.rb, lib/fog/formatador.rb, lib/fog/storage.rb, lib/tasks/test_task.rb, spec/core/collection_spec.rb, spec/formatador_spec.rb, spec/service_spec.rb
@geemus Related to https://github.com/fog/fog-aws/pull/711
=> Fix frozen string literal issue for ruby 3.4

fog-core.gemspec
Here's a patch that excludes files under spec directory from the gem package.
With this patch, the gem package size shrinks as follows:
```
before: 60416 bytes
after:  47104 bytes
```
=> Exclude spec files from gem package
